### ISSUE TITLE
OTRS Community Edition 6.0.18 and otrs.GenerateStats.pl

### ISSUE THREAD

**Issue by github6043** [jelu/otrs#1]
Hi all
We migrated an very old 3.x OTRS to 6.0.18 due to OAuth SMTP issues. So far, this is working. Almos the last issue is calling OTRS reports from crontab. We took the otrs.GenerateStats.pl from the 3.x installation. When running, I get the following error 👍

$Kernel::OM is not defined, please initialize your object manager at /opt/otrs/Kernel/System/Log.pm line 63.
        Kernel::System::Log::new("Kernel::System::Log", "LogPrefix", "OTRS-otrs.GenerateStats.pl", "EncodeObject", Kernel::System::Encode=HASH(0x55ed37c4fd28), "ConfigObject", Kernel::Config=HASH(0x55ed37c4fd58), "UserID", ...) called at /opt/otrs/bin/otrs.GenerateStats.pl line 53

Any ideas, thanks for help in advance

**Comment by jelu** [comment]
Try the people that actually owns the project
